README.md, docs/team/brendan.md
Update the READ.me to remove traces of AB3 left over
=> Update the READ.me to customise it for SeeRee2.0

src/main/java/seedu/address/logic/commands/AddScheduleCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ScheduleList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Add add-schedule duplicate meeting error
=> Add duplicate meeting error

src/main/java/seedu/address/logic/commands/AddScheduleCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/EditScheduleCommand.java, src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/schedule/Meeting.java, src/main/java/seedu/address/storage/JsonAdaptedMeeting.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/calendar/CalendarCard.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/commons/util/FileUtilTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
=> UID for Person

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ScheduleList.java, src/main/java/seedu/address/model/schedule/Meeting.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
=> delete command to check if contact exist in schedue

build.gradle
As per https://nus-cs2103-ay2425s1.github.io/website/schedule/week10/project.html#3-deliver-the-alpha-version-v1-4-thu-oct-24th-23-59
=> Enable assertions in build file

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/commons/util/FileUtil.java, src/main/java/seedu/address/storage/AddressBookStorage.java, src/main/java/seedu/address/storage/JsonAddressBookStorage.java, src/main/java/seedu/address/storage/JsonScheduleStorage.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/main/java/seedu/address/storage/JsonSerializableScheduleStorage.java, src/main/java/seedu/address/storage/ScheduleStorage.java, src/main/java/seedu/address/storage/StorageManager.java, src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java, src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
see #87 
in the following code segments, code will throw error for at least one wrong entry in the json file
https://github.com/AY2425S1-CS2103-F13-3/tp/blob/9b6bef00d3958b11b197425e8957270fa6b73a31/src/main/java/seedu/address/storage/JsonSerializableAddressBook.java#L48-L58
https://github.com/AY2425S1-CS2103-F13-3/tp/blob/9b6bef00d3958b11b197425e8957270fa6b73a31/src/main/java/seedu/address/storage/JsonSerializableScheduleStorage.java#L47-L57
---
This pull request introduces several changes to improve error handling and file operations in the `addressbook` and `schedule` storage modules. The most important changes include adding methods to handle corrupted files, enhancing logging for error tracking.
* [`src/main/java/seedu/address/storage/AddressBookStorage.java`](diffhunk://#diff-9167821 …
=> Enhance file error detection and handling

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/util/SampleDataUtil.java
see #90 
Sample data for new users. Delete both addressbook and schedule to generate sample data for both
=> Implement sample data for schedule for new users

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/calendar/CalendarCard.java, src/main/java/seedu/address/ui/calendar/DailySchedulePanel.java, src/main/java/seedu/address/ui/calendar/WeeklySchedulePanel.java, src/main/resources/view/DailyCalendarPanel.fxml, src/main/resources/view/WeeklyCalendarPanel.fxml
=> Implement Daily Schedule List

src/main/java/seedu/address/ui/HelpWindow.java
Add the various implemented schedule commands from v1.2 - v1.4 into the AB3 help command.
=> Add schedule commands into help command

docs/DeveloperGuide.md, docs/diagrams/LoadScheduleActivityDiagram.puml, src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/util/SampleDataUtil.java
=> Fix sample schedule list implementation behvaiour

src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java, src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
Add AddScheduleCommandTest and AddScheduleCommandParserTest.
=> v1.5: Add schedule command and parser tests

docs/DeveloperGuide.md
- Add Edit Schedule command to DG
- Fix formatting in DG
=> Add Edit schedule to DG

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddScheduleCommand.java, src/main/java/seedu/address/logic/commands/DeleteScheduleCommand.java, src/main/java/seedu/address/logic/commands/EditScheduleCommand.java, src/main/java/seedu/address/logic/commands/SeeAllScheduleCommand.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java, src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteScheduleCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java
=> Unit Testing for Delete Schedule Command and Delete Schedule Command Parser

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddScheduleCommand.java, src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java, src/main/java/seedu/address/model/schedule/Meeting.java, src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java, src/test/java/seedu/address/model/schedule/MeetingTest.java
Fix empty schedule field and fix conflicted date/time
=> Fix alpha-bug issues related to add-schedule

docs/AboutUs.md, docs/team/limkaiwei.md, docs/team/quekbingheng.md
Add QuekBingHeng profile to match documentation requirement.
=> Add QuekBingHeng profile and edit LimKaiWei profile

docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/MeetingContactsSequenceDiagram.puml, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/StorageClassDiagram.puml
favourite command:
closes #173 closes #177 closes #184 closes #196 closes #203✅
jar UG usage problem:
closes #174✅
UG n/NAME:
closes #183 closes #204✅
UG p/phone:
closes #187✅
UG find command:
closes #190✅
manual testing cases:
closes #195 closes #235 closes #241✅
tell braindead user that list will ignore characters after the command:
closes #216✅
improve UCs DG
closes #218 (UC1) closes #243 (UC0)✅
more addressbook seeree name replacement
closes #221 closes #234✅
add in ug additional conditions for delete command:
closes #224✅
command summary errors
closes #231✅
delete command incorrect use find command in example:
closes #232✅
typo/grammar n*zis:
closes #239 closes #252✅
---
This pull request includes several updates to the `DeveloperGuide.md` and `UserGuide.md` documentation files, as …
=> Update DG diagrams

src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json, src/test/java/seedu/address/commons/core/ConfigTest.java, src/test/java/seedu/address/commons/core/VersionTest.java, src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java, src/test/java/seedu/address/model/tag/TagTest.java, src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
This pull request includes multiple changes across various test files to enhance test coverage, improve equality checks, and update JSON test data. The most important changes include adding new test cases, modifying existing ones, and updating JSON files for testing purposes.
* [`src/test/java/seedu/address/commons/core/ConfigTest.java`](diffhunk://#diff-20897f5abf9b088215ba369f8684b9ef21ee873bb67d66d2888c54e966cb3503L4-R9): Added new test cases for `equals` method and `getScheduleStorageFilePath` method to ensure comprehensive test coverage. [[1]](diffhunk://#diff-20897f5abf9b088215ba369f8684b9ef21ee873bb67d66d2888c54e966cb3503L4-R9) [[2]](diffhunk://#diff-20897f5abf9b088215ba369f8684b9ef21ee873bb67d66d2888c54e966cb3503R22-R50)
* …
=> Test coverage for multiple more classes

docs/DeveloperGuide.md
This pull request includes updates to the `docs/DeveloperGuide.md` file, adding a new appendix section for planned enhancements. These enhancements aim to improve the application's data handling and user interface.
Planned Enhancements:
* **Loading Schedule Storage**: Modify the flow to check if the address book sample data is generated first. This ensures that when `addressbook.json` is missing but `schedule.json` is valid, the program backs up `schedule.json` and creates a new schedule list from sample data to match the address book.
* **GUI Warning for Data File Read Errors**: Provide a graphical user interface (GUI) warning in addition to logging when data files are not read correctly, enhancing user awareness of the issue.
* **Meeting Sample Data Timing**: Adjust the generation of …
=> Include planned enhancements in DG appendix section

src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
Closes Issue #185. Adds contact indices duplication detection of the same contact when adding schedules.
=> Add duplicate detection for contact indices

docs/DeveloperGuide.md, docs/UserGuide.md, docs/team/jewiteo.md
closes issues #172, #175, #207, #209, #244, #251, #253, #254, #256
add jewiteo's profile.
- \+ Mention enhancement to UI to accomodate long inputs. Address #209, #251, #253
- \+ Mention enhancement to UI to display favourite at the top of the list. Addresses #254 
- \+ Mention enhancement to UI to shift Sunday as the first day to be displayed instead of monday. Address #207, #244
- \+ Mention enhancement to UI to modify schedule display. Addresses #172
- \- Removed mention of Archiving as a proposed feature.
- \+ Mention known issue of not saving preference to maximize application. Addresses #175
- \+ Mention known issue of scrollbar causing white boxes to appear in the application. Addresses #172
- \- Removed mention of Archiving as a proposed feature. Addresses #256
=> Update documentation of UI
